name: test-FV-327

on:
  workflow_dispatch:
    inputs:
      param1:
        description: "param1"
        required: true
        default: "1.0.0"
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Empfangene Parameter anzeigen
        run: |
          echo "param1: ${{ github.event.inputs.param1 }}"
      - name: Dispatch an other repository workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN2 }}
          # token: ${{ secrets.GITHUB_TOKEN }}
          repository: it-at-m/dave-backend  # Ersetze durch das Ziel-Repository
          event-type: custom_event
          client-payload: |
            {
              "param1": "${{ github.event.inputs.param1 }}"
            }