name: trigger-release-actions2
permissions:
  contents: read
  workflows: write


on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version number to be released (e.g., 1.2.3)"
        required: true
        default: "8.0.0"
      developmentVersion:
        description: "Next version number with snapshot (e.g., 1.2.4-SNAPSHOT)"
        required: true
        default: "8.0.1-SNAPSHOT"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Show input parameters
        run: |
          echo "releaseVersion: ${{ github.event.inputs.releaseVersion }}"
          echo "developmentVersion: ${{ github.event.inputs.developmentVersion }}"

      - name: Dispatch an other repository workflows
        run: |
          # List of repositories
          repositories=("it-at-m/dave-backend" "it-at-m/dave-frontend" "it-at-m/dave-geodata-eai" "it-at-m/dave-document-storage" "it-at-m/dave-admin-portal" "it-at-m/dave-selfservice-portal" "it-at-m/dave-eai")
          
          # Iterate over each repository
          for repo in "${repositories[@]}"; do
            echo "Dispatching to repository: $repo"

            # call repository-dispatch action via github api
            curl -X POST \
              -H "Authorization: token ${{ secrets.FINE_GRAINED_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$repo/dispatches \
              -d '{
                "event_type": "trigger_release_action",
                "client_payload": {
                  "releaseVersion": "${{ github.event.inputs.releaseVersion }}",
                  "developmentVersion": "${{ github.event.inputs.developmentVersion }}"
                }
              }'
          done